"""Constantes globales du jeu (écran, manettes, timings)."""
import pygame

WIDTH, HEIGHT = 1920, 1080

JOY_DEADZONE = 0.35
KEYBOARD_MOVE_MULT = 0.5
JOY_BTN_JUMP = 0
JOY_BTN_SPECIAL = 1
JOY_BTN_ATTACK = 2
JOY_BTN_GRAB = 3
JOY_BTN_COUNTER = 5
JOY_BTN_COUNTER_ALT = 7
JOY_BTN_START = 9

CAMERA_LERP = 0.08

COUNTDOWN_DURATION_MS = 1000

WAIT_AFTER_GIF_MS = 2000
WAIT_AFTER_P1_CONFIRM_MS = 2000
WAIT_AFTER_ENTER_GIF_MS = 2000
WAIT_AFTER_ENTER_THEN_A_MS = 2000

DEBUG_JOYSTICK = True
DEBUG_JOYSTICK_VERBOSE = True
DEBUG_JOYSTICK_VERBOSE_INTERVAL = 30
DEBUG_HUD_BLACK = False
